-- =============================================================================
-- MindNest — Enable pgvector + Knowledge Base
-- Migration: 20260422000000_enable_pgvector_and_knowledge_base.sql
-- =============================================================================
-- Enables the pgvector extension and creates the knowledge_documents table
-- used for Nest AI's RAG (Retrieval-Augmented Generation) pipeline.
-- Embeddings are generated by Voyage AI voyage-3-lite (1024 dimensions).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS vector
  SCHEMA extensions;

-- ---------------------------------------------------------------------------
-- knowledge_documents — stores embedded reference content for RAG retrieval
-- ---------------------------------------------------------------------------
CREATE TABLE public.knowledge_documents (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  title      TEXT        NOT NULL,
  content    TEXT        NOT NULL,
  source     TEXT        NOT NULL,
  category   TEXT        NOT NULL CHECK (category IN ('WHO', 'AAP', 'CDC', 'Research', 'General')),
  embedding  extensions.vector(1024),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE  public.knowledge_documents           IS 'RAG knowledge base — embedded reference documents for Nest AI';
COMMENT ON COLUMN public.knowledge_documents.source    IS 'Original source name or URL of the document';
COMMENT ON COLUMN public.knowledge_documents.category  IS 'Authoritative source category: WHO, AAP, CDC, Research, or General';
COMMENT ON COLUMN public.knowledge_documents.embedding IS 'Voyage AI voyage-3-lite embedding (1024 dimensions)';

-- HNSW index — faster queries than ivfflat; no need to set lists parameter
CREATE INDEX idx_knowledge_documents_embedding
  ON public.knowledge_documents
  USING hnsw (embedding extensions.vector_cosine_ops);

-- RLS — authenticated users can read; only service role can write
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "knowledge_documents_authenticated_read" ON public.knowledge_documents
  FOR SELECT
  TO authenticated
  USING (true);

-- ---------------------------------------------------------------------------
-- match_knowledge_documents — cosine similarity search function
-- Called by /api/knowledge/search via supabase.rpc()
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION match_knowledge_documents(
  query_embedding extensions.vector(1024),
  match_count     INT DEFAULT 3
)
RETURNS TABLE (
  id         UUID,
  title      TEXT,
  content    TEXT,
  source     TEXT,
  category   TEXT,
  similarity FLOAT
)
LANGUAGE sql STABLE
AS $$
  SELECT
    id,
    title,
    content,
    source,
    category,
    1 - (embedding <=> query_embedding) AS similarity
  FROM public.knowledge_documents
  ORDER BY embedding <=> query_embedding
  LIMIT match_count;
$$;
